### ISSUE TITLE
USER STORY: README - Design

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#10]
As a developer I can document the design phase of the project, from the initial planning through the wireframes to the final design choices. I can also document any changes in the design which can often occur throughout development

**Tasks**

- [x]  Add wireframes to README
- [x]  Add colour scheme to README
- [x]  Add font choices to README
