### ISSUE TITLE
USER STORY: Database Models

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#12]
As a developer I can create an entity relationship diagram to help with the structure of the database and link the relevant information to each other. This will allow for a smoother overall development of the site. 

**Acceptance Criteria**

- Create a clear and concise ERD which will accurately display the models and how they are connected. 

**Tasks**

- [x] Create and plan each model for the site.
- [x] Design a diagram to show this information. 
- [x] Add ERD to the README
