### ISSUE TITLE
USER STORY: Create Apps 

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#13]
As a developer I can create multiple apps within the overall project to create various containers for each of the aspects and areas of the site. 

**Tasks**

- [x] Create home app
- [x] Create bag app
- [x] Create checkout app
- [x] Create users app
- [x] Create newsletter app
- [x] Create puzzle_exchange app
- [x] Create products app
- [x] Create messages app
