### ISSUE TITLE
USER STORY: Site Navigation

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#14]
As a user I can navigate the site using a navbar located at the top of the page. By using this I can access the home page, all products and the puzzle exchange. 

I can also log in to my account from here or create an account if I have not yet done so.

**Acceptance criteria**

- A navbar must be at the top of the page to allow for easy access and navigation throughout the site.
- There must be links for the home page, all products and puzzle exchange. 
- User must also be able to log in/create an account from the navbar

**Tasks**

- [x]  Create an includes folder in the directory.
- [x]  Create navigation.html for the navbar and link to it in the base.html using 'includes'
- [x]  Add links to the index.html, products.html, puzzle_exchange.html, about_us.html and faq.html
