### ISSUE TITLE
USER STORY: Products Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#15]
As a user I can view all of the products on one page, I can look through the products using pagination. I can see a preview image of the item along with its price.  Clicking on any of the products will bring me to the product page. 

**Acceptance Criteria**

- Products page must clearly list all available products on the site. 
- Pagination is used for better user experience. 
- Each product must have a preview image and a price. 
- Clicking on a product will bring the user to its dedicated page. 

**Tasks**

- [x] Create a products.html which extends base.html. 
- [x] Display all products in the database using pagination. 
- [x] Add preview image for product and price. 
- [x] Add a link to product page for each item. 
- [x] Finalise CSS/Design for page
