### ISSUE TITLE
USER STORY: Product Details Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#16]
As a user I can see all of the information about a product on it's page. When viewing this page the following information is available to me - Product image, product price, produce details and product rating. From this page I can add a chosen quantity of the item to my basket, I can also leave a review and rating for the product should I wish to, I can also see other user's reviews and ratings. 

**Acceptance Criteria**

- Display product image clearly on the page. 
- Product description is clear and concise. 
- User ratings and reviews are available to read. 
- User can add their own rating and review to the product page. 
- User can select a quantity of the item. 
- User can add the item to their basket. 

**Tasks**

- [x] Create product_details.html which extends base.html .
- [x] Add product image and information to the page. 
- [x] Display average rating for the product using ratings from other users. 
- [x] Display user reviews. 
- [x] Button to add own reviews to page. 
- [x] Add quantity selector to page
- [x] Create a button which will add item to basket. 
- [x] Finalise CSS/Overall page design
