### ISSUE TITLE
USER STORY: Add a product

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#17]
As a site admin I can add a new product to the database which can then by viewed by the users on various dedicated pages. 

**Acceptance Criteria**

- Site admins are able to add more products to the page through the admin panel.

**Tasks**

- [x] Create a products model with various fields. 
- [x] Register model with admin panel. 
- [ ] Install Django summernote to improve admin panel text editor. 
- [ ] Add a product to the database.
