### ISSUE TITLE
USER STORY: Create Fixtures

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#18]
As a developer I can upload a bulk of data to my Django database during the initial development stages using fixtures, this allows for a quicker and more convenient means of adding data to the site. 

**Acceptance Criteria**

- Fixtures must be formatted into easily readable and editable JSON format. 
- Each product must match to primary key in categories fixture. 

**Tasks**

- [x] Create a fixtures folder in the products app.
- [x] Add a fixture for categories
- [x] Add a fixture for products
