### ISSUE TITLE
USER STORY: Delete a product

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#21]
As a site manager I can delete a product through the front end of the site using a dedicated page for authorised users.

**Acceptance Criteria**

- Page must only be accessible to authorised superusers
- Prompt user to confirm if they are certain they wish to delete the product
- Database must update and product no longer available

**Tasks**

- [x]  Create a delete_product.html which extends base.html
- [x]  Only authorised superusers can access page
- [x]  Create a button to delete product
- [x]  Confirm product is no longer in the database
