### ISSUE TITLE
USER STORY: Add a Footer

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#23]
As a developer I can create and design a footer which will allow the user to easily access any external links, contact information for the site and sign up for the newsletter. 

**Acceptance Criteria**

- Footer must not distract from the overall site but still easily accessible to user
- Must contain any external links to social media platforms
- User can sign up for newsletter
- User can contact site owners through contact us

**Tasks**

- [x] Create a footer.html within the includes folder
- [x] Add links to social media platforms
- [x] Add link to contact us page
- [x] Add link to FAQ page
