### ISSUE TITLE
USER STORY: FAQ Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#24]
As a user I can access a FAQ page where I am able to view commonly asked questions by fellow users. 

**Acceptance Criteria**

- FAQ page must be accessible from the navbar
- Layout clear and concise for user
- Option to search for a word or phrase in order to filter FAQs

**Tasks**

- [x] Create a faq.html which extends base.html
- [x] Create a list of questions and answers for users to view
- [x] Finalise CSS/Overall design of the page
