### ISSUE TITLE
USER STORY: Puzzle Exchange Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#25]
As a user I can access a forum style page where I can view posts from other users who are looking to exchange puzzles. I can also submit a puzzle here to exchange with users. 

**Acceptance Criteria**

- Clear defined list of posts by other users who wish to exchange puzzles
- User can click on a post and be brought to a page with further information
- Submit button which opens a form for the user to add their own post
- Sort through posts by date created
- User can navigate posts with pagination

**Tasks**

- [x] Create a puzzle_exchange.html which extends base.html
- [x] Add link to page on navbar
- [x] Create a list to display posts by users
- [x] Add a button which directs for submit_puzzle form
- [x] Add pagination
- [x] Only logged in users can access page
- [x] Finalise CSS/Design
