### ISSUE TITLE
USER STORY: Filter Products By Category

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#27]
As a user I can select the puzzle drop down and choose from various categories and the list will update accordingly. 

**Acceptance Criteria**

- Display a list of product categories in a drop down menu
- Product list should update and display only products which match the category. 

**Tasks**

- [x] Add dropdown menu to navbar
- [x] Create a list within dropdown for categories
- [x] Update product list view to display only products in category
