### ISSUE TITLE
USER STORY: Add Product to Bag

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#28]
As a user I can click on a 'Add to Cart' button and my chosen item will be added to my shopping bag, a notification will also display to advise that it has been added to the bag. I can also choose a quantity for the product should I wish to. 

**Acceptance Criteria**

- Add to Cart button must be easily accessible and function correctly. 
- When an item has been added to the bag a message should be displayed to the user advising as such.
- Quantity selector for choosing how many of a product to be added to bag. 

**Tasks**

- [x] Add a button to product_details.html which will add product to bag object.
- [x] Add a quantity selector beside button. 
- [x] Use Django messages to notify user when adding an item to their bag
