### ISSUE TITLE
USER STORY: Create Shopping Bag Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#29]
As a user I can see all of the products I wish to buy in my shopping bag, from here I can also choose to go to the checkout. 

**Acceptance Criteria**

- User must be able to see a dedicated page for their shopping bag when clicking on bag icon. 
- Page must have all chosen products and their quantity displayed alongside product name and price. 

**Tasks**

- [x] Create shopping_bag.html which extends base.html
- [x] Create bag object to store the user's products using current session. 
- [x] Display product name, price and quantity clearly for user. 
- [x] Display bag summary and link to bag page on header. 
- [x] Add button to take user to secure checkout for purchase.
