### ISSUE TITLE
USER STORY: Deploy to Heroku 

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#3]
As a developer I can deploy my project to Heroku after the initial set up to ensure that everything works correctly so that the project can be tested as it is being developed. 

**Acceptance criteria**

Must successfully display the live site with no errors. 

**Tasks**

- [x]  Create an app for Perfect Fit on Heroku.
- [x]  Add the secret keys to config values.
- [x]  Set up requirments.txt file.
- [x]  Create Heroku Procfile
- [x]  Deploy to main branch
