### ISSUE TITLE
USER STORY: Sort Bar

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#34]
As a user I can sort the products even further by choosing an option from a dropdown menu

**Acceptance Criteria**

- Display a dropdown with various sorting filters
- Only display relevant products.

**Tasks**

- [x] Add a selector bar to the all_products.html page.
- [x] Add options to sort products various terms in ascending and descending values such as price. 
- [x] Add JavaScript for functionality
