### ISSUE TITLE
USER STORY: About Us Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#35]
As a user I can learn more about 'Perfect Fit' through the 'About Us' page. 

**Acceptance Criteria**

- Simple and clear design so the focus is on the about us page content

**Tasks**

- [x] Create an about_us.html which extends base.html
- [x] Add about us content
- [x] Add hero image to compliment content
- [x] Finalise design/CSS
