### ISSUE TITLE
USER STORY: Toast Notifications

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#37]
As a user I can I see a notification whenever I add an item to my bag, remove the item or updating the quantity.

**Acceptance Criteria**

- Notifications must be clearly visible to the user. 
- Must be relevant to the action which triggers them. 

**Tasks**

- [x] Create Toast notifications for adding items to bag.
- [x] Create Toast notifications for removing items to bag.
- [x] Create Toast notifications for updating item quantity
- [x] Test each notification to ensure it works.
