### ISSUE TITLE
USER STORY: Log In Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#39]
As a registered user I can easily log in to my account, there should be an option to log in on the navigation bar which can be accessed from any page.

**Acceptance criteria**

- A user who has an account, but is not logged in, must be able to easily log in to the site.
- Log in button should be accessible on the navigation bar
- Navigation bar must update to display that user is logged in.

**Tasks**

- [x]  Add a 'Log In' button on the navbar
- [x]  Direct user to 'Log In' page when option is clicked. 
- [x]  Add link to 'Sign Out' page via drop down when user clicks user icon
- [x]  Finalise page design/CSS
