### ISSUE TITLE
USER STORY: Sign Up Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#40]
As a guest user I can easily create my own account for saving order records, there should be an option to sign up on the navigation bar which can be accessed from any page.

**Acceptance criteria**

- A new user must be able to easily create an account.
- Sign Up button should be accessible on the navigation bar
- Should direct user to Log In page after account is created

**Tasks**

- [x]  Add a 'Sign Up button on the navbar
- [x]  Direct user to 'Sign Up' page when option is clicked.
- [x]  Direct user to 'Log In' page once account has been created.
- [x]  Add link to 'Sign Out' page via drop down when user clicks user icon
- [x]  Finalise page design/CSS
