### ISSUE TITLE
USER STORY: Log Out Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#41]
As a logged in user I can easily sign out of my account, when clicking on 'My Account' there should be an option to log out

**Acceptance criteria**

- A logged in user must be easily able to sign out.
- Log Out button should be accessible on the navigation bar
- Should direct user to Log Out page after account is created

**Tasks**

- [x]  Add a 'Log Out' button on the navbar
- [x]  Direct user to 'Log Out' page when option is clicked.
- [x]  Direct user to back to home page once logged out.
- [x]  Finalise page design/CSS
