### ISSUE TITLE
USER STORY: Stripe Implementation

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#42]
As a developer I can ensure a secure payment process for users through the implementation of Stripe. 

**Acceptance Criteria**

- Stripe must be implemented at the checkout to ensure secure orders. 
- Using webhooks confirmation emails must be sent to the user

**Tasks**

- [x] Using Stripe documentation, set up necessary code for online payments. 
- [x] Set up webhooks to confirm payments. 
- [x] Create confirmation emails when orders have been completed.
