### ISSUE TITLE
USER STORY: Update Shopping Bag Quantity

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#44]
As a user I can add more of the same item to my shopping bag through a quantity selector on the shopping bag page to save time by not going back to the item page. 

**Acceptance Criteria**

- Easily add more of the same product to the shopping bag from the shopping bag page. 
- Update bag total to reflect price change. 
- Notify user that the bag has been updated. 

**Tasks**

- [x] Add a button to update the quantity of an item.
- [x] Refresh shopping bag page with new updated quantity. 
- [x] Notify user that their shopping bag has been updated.
