### ISSUE TITLE
USER STORY: Remove item from shopping bag

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#45]
As a user I can remove an item from my bag through the shopping bag page. 

**Acceptance Criteria**

- Easily remove a chosen product from the bag on the shopping bag page. 
- Update bag total to reflect price change. 
- Notify user that product has been removed. 

**Tasks**

- [x] Add a button to remove the quantity of an item.
- [x] Refresh shopping bag page with new updated quantity. 
- [x] Notify user that their shopping bag has been updated.
