### ISSUE TITLE
USER STORY: Checkout Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#47]
As a user I can complete my purchase through a checkout page, here I can fill in my delivery details and payment information. 

**Acceptance Criteria**

- Clear and easy to fill in form for user's delivery information.
- Use Stripe to fill in payment information. 

**Tasks**

- [x] Create a checkout.html which extends base.html
- [x] Add a form to add delivery information
- [x] Allow logged in users to save delivery information. 
- [x] Implement Stripe for a secure means of taking payment information. 
- [x] Finalise design/CSS
