### ISSUE TITLE
USER STORY: Order Confirmation Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#49]
As a user I can view a summary of my order along with my order number and confirmation that the order has gone through successfully.  As an authenticated user I can also access the puzzle exchange from here if I wish to trade any current puzzles I own. 

**Acceptance Criteria**

- Display clear information on user's order.
- Link to visit Puzzle Exchange for logged in users. 

**Tasks**

- [x] Create a checkout_success.html which extends base.html
- [x] Display order summary to the user. 
- [x] Add link to puzzle_exchange.html to logged in users only.
