### ISSUE TITLE
USER STORY: Custom 404 page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#56]
As a user, if I navigate to a page that does not exist I will be presented with a 404 error page advising me and can be directed back to the products page. 

**Acceptance Criteria**

- Must be clear and concise in layout
- Redirect user to products page. 

**Tasks**

- [x] Create a 404.html which extends base.html
- [x] Add a view for 404 in Perfect Fit app
- [x] Test 404 page works when deployed
