### ISSUE TITLE
USER STORY: Home Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#6]
As a user I can view the home page for this site, once here I can learn more about the shop, navigate to other pages, browse all products, from here I can also log in to the site or  create an account.

**Acceptance criteria**

- The home page must make it clear to the user the purpose of the store
- User must be able to click a link which will bring them to all the products available
- Through the use of a navbar the user must be able to access other pages 
- A user must be able to log in to their account or create an account from here.

**Tasks**

- [x]  Create a index.html which extends the base.html
- [x]  Create a clear home page design which will easily show the purpose of the store.
- [x]  Add a link to view all products on the store
- [x]  Add a navigation bar to the home page to access other pages.
- [x]  Finalise CSS/Design for page
