### ISSUE TITLE
USER STORY: Message System for Puzzle Exchange

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#64]
As a logged in user I can send a message notify the user that I wish to trade puzzles with them, I can also receive a notification if a user sends me a message

**Acceptance Criteria**

- Add a comments section to puzzle_detail
- When a comment has been added to a user's post they are alerted.

**Tasks**

- [x] Create a form to submit messages to another user.
- [x] Add a button to link to message_form
- [x] Create a view to notify user's if they have received a message

To add in future 
- System to reply to a user's notification which will then notify them via email.
