### ISSUE TITLE
USER STORY: Contact Us Email

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#67]
As a user I can send a query to Perfect Fit through a contact us page and receive a confirmation email so I know the team are working on it. 

**Acceptance Criteria**

- Easily accessible form for sending a query. 
- Receive a confirmation email after submitting. 

**Tasks**

- [x] Create a contact us model.
- [x] Create a contact_us page that extends base.html
- [x] Create a contact_success page to display after submitting an email . 
- [x] Send a confirmation email after query has been submitted. 
- [x] Test on live site.
