### ISSUE TITLE
USER STORY: README - Design Methodologies

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#8]
As a developer I can build a project using agile development, this will aid in the planning of the project to ensure the design scope and user goals are aligned throughout development. 

**Tasks**

- [x]  Discuss Agile development as a methodology
- [x]  Add Epics to README
- [x]  Discuss EPICS and their relation to User Stories
- [ ]  Add plans for future iterations
