### ISSUE TITLE
USER STORY: README - User Experience

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/perfect-fit#9]
As a developer I can create various user goals/stories which will aid in the development of the project and ensure that the end result caters to the target user and user experience. 

**Tasks**

- [x] Create user goals for first time users
- [x] Create user goals for authenticated users
- [x] Create user goals for site owners
- [x] Document the overall scope of the project.
